[tool.poetry]
name = "ansible_modules"
version = "0.3.1"
description = "Ansible plugins to manage and interact with NetBox"
authors = ["Mikhail Yohman <mikhail.yohman@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
setuptools = "*"
ansible = "^2.9"
black = "19.10b0"
coverage = "*4.0"
jsondiff = "*"
pynetbox = "*"
cryptography = "*"
jmespath = "*"
codecov = "*"
sphinx = "*"
sphinx_rtd_theme = "*"
antsibull = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
